### PR TITLE
Bazel 0.26.1

### PR DESCRIPTION
**Pull request by lizan**

### CODE REVIEW

**Comment by davido** [comment]
Can we wait until tomorrow and upgrade right to 0.26.1 that is going to be released on Thursday, 6: https://github.com/bazelbuild/bazel/issues/7499#issuecomment-498698772?

**Comment by lizan** [comment]
@davido SGTM

**Comment by lizan** [comment]
@davido updated

**Comment by davido** [comment]
Thanks.

**Comment by lizan** [comment]
Can you make a release? @davido

**Comment by davido** [comment]
> Can you make a release?

Done: https://github.com/davido/bazel-alpine-package/releases/tag/0.26.1.

**Pull request merged**
