### PR TITLE
Bazel 0.21.0

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Review by davido — APPROVED** [review]
Thanks.

**Comment by lizan** [comment]
@davido can you build a new release?

**Comment by davido** [comment]
I will try to release in the next days. Sorry for the delay. I'm busy with other work.

**Update**: building it now, ...

**Comment by davido** [comment]
Done: https://github.com/davido/bazel-alpine-package/releases/tag/0.21.0.

**Comment by lizan** [comment]
@davido Thanks!

**Pull request merged**
